apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    # works because the Istio CR is named `default` with the InPlace update
    # strategy, so its active revision is also named `default`
    istio-injection: enabled
